[package]
name = "rust_audio"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_audio"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cpal = "0.15"
anyhow = "1"

[[bin]]
name = "realtime_player"
path = "src/main.rs"
